// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// doub_lab_c
IntegerVector doub_lab_c(IntegerMatrix knn_orig, IntegerVector sim_lab, int n_doub, int n_lev);
RcppExport SEXP _Cleanet_doub_lab_c(SEXP knn_origSEXP, SEXP sim_labSEXP, SEXP n_doubSEXP, SEXP n_levSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type knn_orig(knn_origSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type sim_lab(sim_labSEXP);
    Rcpp::traits::input_parameter< int >::type n_doub(n_doubSEXP);
    Rcpp::traits::input_parameter< int >::type n_lev(n_levSEXP);
    rcpp_result_gen = Rcpp::wrap(doub_lab_c(knn_orig, sim_lab, n_doub, n_lev));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_Cleanet_doub_lab_c", (DL_FUNC) &_Cleanet_doub_lab_c, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_Cleanet(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
