# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doub_lab_c <- function(knn_orig, sim_lab, n_doub, n_lev) {
    .Call(`_Cleanet_doub_lab_c`, knn_orig, sim_lab, n_doub, n_lev)
}

